### ISSUE TITLE
Move to DataStructures.jl

### ISSUE THREAD

**Issue by kmsquire** [JuliaAttic/Trie.jl#1]
This would probably be better as part of DataStructures.jl.

**Comment by milktrader** [comment]
Either that or change the name of the package to `Tries.jl` and the src/ file to `Tries.jl` since the current naming is not exposing the type.

**Comment by aviks** [comment]
Created a PR to move this to DataStructures. https://github.com/JuliaLang/DataStructures.jl/pull/14

Any objections?

**Comment by quinnj** [comment]
+1

**Comment by nolta** [comment]
I wrote this code, and i have no objections.

**Comment by milktrader** [comment]
+1

**Comment by StefanKarpinski** [comment]
For a while, we can leave this as a shim package that simply depends on and imports DataStructures and then exports the Trie data structure. That way code that uses the Trie package won't break right away. It can print a deprecation warning when you load it, telling you to use the DataStructures package instead.
